version: 1.0.0
name: intl_phone_field
description: A customized Flutter TextFormField to input international phone number along with country code.
homepage: https://github.com/vanshg395/intl_phone_field

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flag: ^7.0.0
  phone_numbers_parser: ^8.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: 
